services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 123123  
      DB_NAME: desafio_taghos
      DB_SSLMODE: disable
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy  

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: desafio_taghos
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  pgdata:
